(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TestRtcApi) {
      root.TestRtcApi = {};
    }
    root.TestRtcApi.Channels = factory(root.TestRtcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Channels model module.
   * @module model/Channels
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Channels</code>.
   * A media channel in an agent&#39;s test run
   * @alias module:model/Channels
   * @class
   * @param name
   * @param direction
   * @param type
   */
  var exports = function(name, direction, type) {

    this['name'] = name;
    this['direction'] = direction;
    this['type'] = type;

  };

  /**
   * Constructs a <code>Channels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Channels} obj Optional instance to populate.
   * @return {module:model/Channels} The populated <code>Channels</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) { 
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('direction')) {
        obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('codec')) {
        obj['codec'] = ApiClient.convertToType(data['codec'], 'String');
      }
    }
    return obj;
  }


  /**
   * The name of the channel. Usually this would be the SSRC generated by the browser for the channel, if it is available
   * @member {String} name
   */
  exports.prototype['name'] = undefined;

  /**
   * Can be either 'in' or 'out'
   * @member {String} direction
   */
  exports.prototype['direction'] = undefined;

  /**
   * Can be either 'audio' or 'video'
   * @member {String} type
   */
  exports.prototype['type'] = undefined;

  /**
   * The audio or video codec used in the channel
   * @member {String} codec
   */
  exports.prototype['codec'] = undefined;




  return exports;
}));
