/**
 * testRTC API
 * testRTC's API for WebRTC service monitoring and testing automation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@testrtc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TestRtcApi) {
      root.TestRtcApi = {};
    }
    root.TestRtcApi.MachineProfile = factory(root.TestRtcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MachineProfile model module.
   * @module model/MachineProfile
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MachineProfile</code>.
   * Machine profile for the test
   * @alias module:model/MachineProfile
   * @class
   * @param browser {String} The browser used for the test
   * @param location {String} The data center used for the test
   * @param networkProfile {String} The network profile used by the test
   * @param firewallProfile {String} The firewall profile used by the test
   * @param media {String} The media file used by this test
   */
  var exports = function(browser, location, networkProfile, firewallProfile, media) {
    var _this = this;

    _this['browser'] = browser;
    _this['location'] = location;
    _this['networkProfile'] = networkProfile;
    _this['firewallProfile'] = firewallProfile;
    _this['media'] = media;
  };

  /**
   * Constructs a <code>MachineProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MachineProfile} obj Optional instance to populate.
   * @return {module:model/MachineProfile} The populated <code>MachineProfile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('browser')) {
        obj['browser'] = ApiClient.convertToType(data['browser'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('networkProfile')) {
        obj['networkProfile'] = ApiClient.convertToType(data['networkProfile'], 'String');
      }
      if (data.hasOwnProperty('firewallProfile')) {
        obj['firewallProfile'] = ApiClient.convertToType(data['firewallProfile'], 'String');
      }
      if (data.hasOwnProperty('media')) {
        obj['media'] = ApiClient.convertToType(data['media'], 'String');
      }
    }
    return obj;
  }

  /**
   * The browser used for the test
   * @member {String} browser
   */
  exports.prototype['browser'] = undefined;
  /**
   * The data center used for the test
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * The network profile used by the test
   * @member {String} networkProfile
   */
  exports.prototype['networkProfile'] = undefined;
  /**
   * The firewall profile used by the test
   * @member {String} firewallProfile
   */
  exports.prototype['firewallProfile'] = undefined;
  /**
   * The media file used by this test
   * @member {String} media
   */
  exports.prototype['media'] = undefined;



  return exports;
}));


