/**
 * testRTC API
 * testRTC's API for WebRTC service monitoring and testing automation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@testrtc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StatusPageConfig', 'model/StatusPageRole'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StatusPageConfig'), require('./StatusPageRole'));
  } else {
    // Browser globals (root is window)
    if (!root.TestRtcApi) {
      root.TestRtcApi = {};
    }
    root.TestRtcApi.StatusPage = factory(root.TestRtcApi.ApiClient, root.TestRtcApi.StatusPageConfig, root.TestRtcApi.StatusPageRole);
  }
}(this, function(ApiClient, StatusPageConfig, StatusPageRole) {
  'use strict';




  /**
   * The StatusPage model module.
   * @module model/StatusPage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>StatusPage</code>.
   * A Status page object includes detailed information about service status.
   * @alias module:model/StatusPage
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>StatusPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatusPage} obj Optional instance to populate.
   * @return {module:model/StatusPage} The populated <code>StatusPage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('role')) {
        obj['role'] = StatusPageRole.constructFromObject(data['role']);
      }
      if (data.hasOwnProperty('config')) {
        obj['config'] = StatusPageConfig.constructFromObject(data['config']);
      }
      if (data.hasOwnProperty('queueStatus')) {
        obj['queueStatus'] = ApiClient.convertToType(data['queueStatus'], 'String');
      }
      if (data.hasOwnProperty('queueCount')) {
        obj['queueCount'] = ApiClient.convertToType(data['queueCount'], 'Integer');
      }
      if (data.hasOwnProperty('dbStatus')) {
        obj['dbStatus'] = ApiClient.convertToType(data['dbStatus'], 'String');
      }
      if (data.hasOwnProperty('dbCount')) {
        obj['dbCount'] = ApiClient.convertToType(data['dbCount'], 'Integer');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/StatusPageRole} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {module:model/StatusPageConfig} config
   */
  exports.prototype['config'] = undefined;
  /**
   * The status of queue
   * @member {String} queueStatus
   */
  exports.prototype['queueStatus'] = undefined;
  /**
   * The queue count
   * @member {Integer} queueCount
   */
  exports.prototype['queueCount'] = undefined;
  /**
   * The queue status
   * @member {String} dbStatus
   */
  exports.prototype['dbStatus'] = undefined;
  /**
   * The database count
   * @member {Integer} dbCount
   */
  exports.prototype['dbCount'] = undefined;
  /**
   * The status of service, indicates working status.
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


