/**
 * testRTC API
 * testRTC's API for WebRTC service monitoring and testing automation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@testrtc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TestRtcApi) {
      root.TestRtcApi = {};
    }
    root.TestRtcApi.StatusPageConfig = factory(root.TestRtcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StatusPageConfig model module.
   * @module model/StatusPageConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>StatusPageConfig</code>.
   * The configuration of current environment
   * @alias module:model/StatusPageConfig
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>StatusPageConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatusPageConfig} obj Optional instance to populate.
   * @return {module:model/StatusPageConfig} The populated <code>StatusPageConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('systemName')) {
        obj['systemName'] = ApiClient.convertToType(data['systemName'], 'String');
      }
      if (data.hasOwnProperty('instanceName')) {
        obj['instanceName'] = ApiClient.convertToType(data['instanceName'], 'String');
      }
      if (data.hasOwnProperty('agentVersion')) {
        obj['agentVersion'] = ApiClient.convertToType(data['agentVersion'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
    }
    return obj;
  }

  /**
   * The system name of environment
   * @member {String} systemName
   */
  exports.prototype['systemName'] = undefined;
  /**
   * The name of instance
   * @member {String} instanceName
   */
  exports.prototype['instanceName'] = undefined;
  /**
   * The version of agent
   * @member {String} agentVersion
   */
  exports.prototype['agentVersion'] = undefined;
  /**
   * The current version
   * @member {String} version
   */
  exports.prototype['version'] = undefined;



  return exports;
}));


